# Generated by Django 5.2.6 on 2025-11-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_birthday_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateTimeField(blank=True, null=True, verbose_name="생년월일"),
        ),
    ]
